{{ rails_environment }}:
  adapter: mysql2
  encoding: utf8
  host: <%= ENV['database_hostname'] %>
  database: <%= ENV['database_name'] %>
  pool: {{ mnohub_config.database.pool }}
  timeout: {{ mnohub_config.database.timeout }}
  username: <%= ENV['database_username'] %>
  password: <%= ENV['database_password'] %>
