---

- name: Maestrano | Detect if initial setup
  stat:
    path: "{{deploy_directory}}"
  register: deploy_directory_path

- name: Maestrano | Setup RDS instance
  include: rds.yml

- name: Maestrano | Initial application setup
  include: initial_setup.yml

- name: Maestrano | Deploy application version
  include: deploy.yml
  tags: [deploy]

- name: Maestrano | Run/Reload Puma (Debian)
  include: puma_deb.yml
  when: ansible_os_family == "Debian"

- name: Maestrano | Run/Reload Puma (RHEL)
  include: puma_rhel.yml
  when: ansible_os_family == "RedHat"
