---

- name: Maestrano | Add /etc/init/puma.conf
  template: src=etc_init_puma.conf dest=/etc/init/puma.conf force=yes mode=0755

- name: Maestrano | Add /etc/init/delayed-job.conf
  template: src=etc_init_delayed-job.conf dest=/etc/init/delayed-job.conf force=yes mode=0755

- name: Maestrano | Add Puma to upstart
  service: name=puma state=started enabled=yes

- name: Maestrano | Add DelayedJob to upstart
  service: name=delayed-job state=started enabled=yes
