- name: JRuby | Check jruby installation
  stat:
    path: "/opt/torquebox/jruby-{{ jruby.version }}"
  register: jruby_install_path

- name: JRuby | Download
  get_url:
    url: "https://s3.amazonaws.com/jruby.org/downloads/{{ jruby.version }}/jruby-bin-{{ jruby.version }}.tar.gz"
    dest: /tmp/jruby-bin.tar.gz
    mode: 0755
  when: jruby_install_path.stat.exists == False

- name: JRuby | Extract
  command: "creates=/opt/torquebox/jruby-{{ jruby.version }} tar -xzf /tmp/jruby-bin.tar.gz -C /opt/torquebox/"
  when: jruby_install_path.stat.exists == False

- name: JRuby | Replace previous version
  file:
    path: /opt/torquebox/jruby
    state: absent
  when: jruby_install_path.stat.exists == False

- name: JRuby | Symbolic link
  file:
    src: "/opt/torquebox/jruby-{{ jruby.version }}"
    dest: /opt/torquebox/jruby
    owner: "{{ torquebox.owner }}"
    group: "{{ torquebox.group }}"
    state: link
    force: yes
  when: jruby_install_path.stat.exists == False

- name: JRuby | Clean up tar file
  file:
    path: /tmp/jruby-bin.tar.gz
    state: absent
  when: jruby_install_path.stat.exists == False