---

# Maestrano Configuration

- set_fact: maestrano_component="maestrano-app-server-local"

- name: Create Maestrano ELB
  ec2_elb_lb:
    name: "{{ maestrano.elastic_load_balancer.name }}"
    state: present
    scheme: "{{ maestrano.elastic_load_balancer.scheme | default('internet-facing')}}"
    connection_draining_timeout: "{{ maestrano.elastic_load_balancer.connection_draining_timeout }}"
    cross_az_load_balancing: "yes"
    region: "{{ aws_region }}"
    ec2_access_key: "{{ aws_access_key }}"
    ec2_secret_key: "{{ aws_secret_key }}"
    subnets: "{{ maestrano.elastic_load_balancer.subnets }}"
    security_group_ids: "{{ maestrano.elastic_load_balancer.security_group_ids }}"
    listeners: "{{ maestrano.elastic_load_balancer.listeners }}"
    health_check: "{{ maestrano.elastic_load_balancer.health_check }}"
  register: maestrano_elastic_load_balancer

- name: Add DNS record for ELB
  route53:
    command: create
    zone: "{{ (route53.zone.name|string) }}"
    record: "{{ maestrano.dns_record.record }}"
    type: "{{ maestrano.dns_record.type }}"
    value: "{{ maestrano_elastic_load_balancer.elb.dns_name }}"
    alias: "{{ maestrano.dns_record.alias }}"
    ttl: "{{ maestrano.dns_record.ttl }}"
    private_zone: "{{ route53.zone.private_zone }}"
    alias_hosted_zone_id: "{{ maestrano.elastic_load_balancer.alias_hosted_zone_id }}"
    overwrite: "{{ maestrano.dns_record.overwrite }}"

- name: Create Maestrano Launch Configuration
  ec2_lc:
    name: "{{ maestrano.launch_configuration.name }}"
    key_name: "{{ maestrano.launch_configuration.key_name }}"
    region: "{{ aws_region }}"
    ec2_access_key: "{{ aws_access_key }}"
    ec2_secret_key: "{{ aws_secret_key }}"
    image_id: "{{ maestrano.launch_configuration.image_id }}"
    instance_type: "{{ maestrano.launch_configuration.instance_type }}"
    security_groups: "{{ maestrano.launch_configuration.security_groups }}"
    user_data: "{{ lookup('template', '../templates/user_data.sh') }}"
    volumes:
      - device_name: /dev/sda1
        volume_size: 50
        device_type: gp2 # SSD
        delete_on_termination: true

- name: Create Maestrano Auto Scaling Group
  ec2_asg:
    name: "{{ maestrano.auto_scaling_group.name }}"
    region: "{{ aws_region }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    launch_config_name: "{{ maestrano.launch_configuration.name }}"
    min_size: "{{ maestrano.auto_scaling_group.min_size }}"
    max_size: "{{ maestrano.auto_scaling_group.max_size }}"
    desired_capacity: "{{ maestrano.auto_scaling_group.desired_capacity }}"
    vpc_zone_identifier: "{{ maestrano.auto_scaling_group.vpc_zone_identifier }}"
    availability_zones: "{{ maestrano.auto_scaling_group.availability_zones }}"
    load_balancers: "{{ maestrano.elastic_load_balancer.name }}"
    tags: "{{ maestrano.auto_scaling_group.tags }}"
  register: maestrano_auto_scaling_group
