---

- name: Connec | Setup deployment directories
  include: setup.yml

- name: Connec | Deploy new version
  include: deploy.yml
  tags: [deploy]

- name: Connec | Gathering EC2 facts
  action: ec2_facts
  tags: [deploy]

- name: Connec | Instance De-register
  ec2_elb:
    instance_id: "{{ ansible_ec2_instance_id }}"
    state: absent
  tags: [deploy]

- name: Connec | Run/Reload Puma/Sidekiq Runtime (Debian)
  include: runtime_deb.yml
  tags: [deploy]
  when: ansible_os_family == "Debian"

- name: Connec | Run/Reload Puma/Sidekiq Runtime (RHEL)
  include: runtime_rhel.yml
  tags: [deploy]
  when: ansible_os_family == "RedHat"

- name: Connec | Instance Register
  ec2_elb:
    instance_id: "{{ ansible_ec2_instance_id }}"
    ec2_elbs: "{{ item }}"
    state: present
  with_items: ec2_elbs
  tags: [deploy]
