---

- name: Connec | Setup deployment directories
  include: setup.yml

- name: Connec | Deploy new version
  include: deploy.yml
  tags: [deploy]

- name: Connec | Run/Reload Puma/Sidekiq Runtime (Debian)
  include: runtime_deb.yml
  tags: [deploy]
  when: ansible_os_family == "Debian"

- name: Connec | Run/Reload Puma/Sidekiq Runtime (RHEL)
  include: runtime_rhel.yml
  tags: [deploy]
  when: ansible_os_family == "RedHat"
